# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ModCheck
                                 A QGIS plugin
 Review, interrogation and assessment tools for hydraulic models
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-23
        copyright            : (C) 2021 by Duncan Runnacles
        email                : info@ermeviewenvironmental.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ModCheck class from file ModCheck.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .menu import Menu
    return Menu(iface)
