# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_assessment_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssessmentDialog(object):
    def setupUi(self, AssessmentDialog):
        AssessmentDialog.setObjectName("AssessmentDialog")
        AssessmentDialog.resize(861, 750)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(AssessmentDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.modelFolderGroupbox = QtWidgets.QGroupBox(AssessmentDialog)
        self.modelFolderGroupbox.setObjectName("modelFolderGroupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.modelFolderGroupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.modelFolderGroupbox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.modelFolderFileWidget = QgsFileWidget(self.modelFolderGroupbox)
        self.modelFolderFileWidget.setStorageMode(QgsFileWidget.GetDirectory)
        self.modelFolderFileWidget.setObjectName("modelFolderFileWidget")
        self.verticalLayout.addWidget(self.modelFolderFileWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reloadBtn = QtWidgets.QPushButton(self.modelFolderGroupbox)
        self.reloadBtn.setAutoDefault(False)
        self.reloadBtn.setObjectName("reloadBtn")
        self.horizontalLayout.addWidget(self.reloadBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addWidget(self.modelFolderGroupbox)
        self.outputsGroupbox = QtWidgets.QGroupBox(AssessmentDialog)
        self.outputsGroupbox.setObjectName("outputsGroupbox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.outputsGroupbox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputTextEdit = QtWidgets.QPlainTextEdit(self.outputsGroupbox)
        self.outputTextEdit.setObjectName("outputTextEdit")
        self.verticalLayout_2.addWidget(self.outputTextEdit)
        self.exportResultsBtn = QtWidgets.QPushButton(self.outputsGroupbox)
        self.exportResultsBtn.setAutoDefault(False)
        self.exportResultsBtn.setObjectName("exportResultsBtn")
        self.verticalLayout_2.addWidget(self.exportResultsBtn)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addWidget(self.outputsGroupbox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.statusLabel = QtWidgets.QLabel(AssessmentDialog)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_2.addWidget(self.statusLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(AssessmentDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AssessmentDialog)
        self.buttonBox.rejected.connect(AssessmentDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AssessmentDialog)
        AssessmentDialog.setTabOrder(self.reloadBtn, self.exportResultsBtn)

    def retranslateUi(self, AssessmentDialog):
        _translate = QtCore.QCoreApplication.translate
        AssessmentDialog.setWindowTitle(_translate("AssessmentDialog", "File Check"))
        self.modelFolderGroupbox.setTitle(_translate("AssessmentDialog", "Model location"))
        self.label.setText(_translate("AssessmentDialog", "Model root folder"))
        self.reloadBtn.setText(_translate("AssessmentDialog", "Reload"))
        self.outputsGroupbox.setTitle(_translate("AssessmentDialog", "Outputs"))
        self.exportResultsBtn.setText(_translate("AssessmentDialog", "Export Results"))
from qgsfilewidget import QgsFileWidget
