# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_fmpsectionproperty_check_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FmpSectionPropertyCheckDialog(object):
    def setupUi(self, FmpSectionPropertyCheckDialog):
        FmpSectionPropertyCheckDialog.setObjectName("FmpSectionPropertyCheckDialog")
        FmpSectionPropertyCheckDialog.resize(635, 558)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(FmpSectionPropertyCheckDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(FmpSectionPropertyCheckDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.datFileWidget = QgsFileWidget(FmpSectionPropertyCheckDialog)
        self.datFileWidget.setObjectName("datFileWidget")
        self.horizontalLayout_4.addWidget(self.datFileWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.datFileReloadBtn = QtWidgets.QPushButton(FmpSectionPropertyCheckDialog)
        self.datFileReloadBtn.setObjectName("datFileReloadBtn")
        self.horizontalLayout.addWidget(self.datFileReloadBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(FmpSectionPropertyCheckDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.fmpNodesLayerCbox = QgsMapLayerComboBox(FmpSectionPropertyCheckDialog)
        self.fmpNodesLayerCbox.setObjectName("fmpNodesLayerCbox")
        self.verticalLayout_3.addWidget(self.fmpNodesLayerCbox)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.conveyanceGroupBox = QtWidgets.QGroupBox(FmpSectionPropertyCheckDialog)
        self.conveyanceGroupBox.setObjectName("conveyanceGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.conveyanceGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.conveyanceGroupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.kTolSpinbox = QgsDoubleSpinBox(self.conveyanceGroupBox)
        self.kTolSpinbox.setProperty("value", 10.0)
        self.kTolSpinbox.setObjectName("kTolSpinbox")
        self.horizontalLayout_2.addWidget(self.kTolSpinbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.negativeConveyanceTable = QtWidgets.QTableWidget(self.conveyanceGroupBox)
        self.negativeConveyanceTable.setObjectName("negativeConveyanceTable")
        self.negativeConveyanceTable.setColumnCount(3)
        self.negativeConveyanceTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.negativeConveyanceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.negativeConveyanceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.negativeConveyanceTable.setHorizontalHeaderItem(2, item)
        self.negativeConveyanceTable.horizontalHeader().setDefaultSectionSize(150)
        self.negativeConveyanceTable.horizontalHeader().setMinimumSectionSize(150)
        self.negativeConveyanceTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.negativeConveyanceTable)
        self.verticalLayout_4.addWidget(self.conveyanceGroupBox)
        self.groupBox = QtWidgets.QGroupBox(FmpSectionPropertyCheckDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.bankDyToleranceSpinbox = QgsDoubleSpinBox(self.groupBox)
        self.bankDyToleranceSpinbox.setMinimum(0.01)
        self.bankDyToleranceSpinbox.setMaximum(1.0)
        self.bankDyToleranceSpinbox.setSingleStep(0.1)
        self.bankDyToleranceSpinbox.setProperty("value", 0.1)
        self.bankDyToleranceSpinbox.setObjectName("bankDyToleranceSpinbox")
        self.horizontalLayout_3.addWidget(self.bankDyToleranceSpinbox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.banktopCheckTable = QtWidgets.QTableWidget(self.groupBox)
        self.banktopCheckTable.setObjectName("banktopCheckTable")
        self.banktopCheckTable.setColumnCount(3)
        self.banktopCheckTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.banktopCheckTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.banktopCheckTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.banktopCheckTable.setHorizontalHeaderItem(2, item)
        self.banktopCheckTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.banktopCheckTable)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(FmpSectionPropertyCheckDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(FmpSectionPropertyCheckDialog)
        self.buttonBox.accepted.connect(FmpSectionPropertyCheckDialog.accept)
        self.buttonBox.rejected.connect(FmpSectionPropertyCheckDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FmpSectionPropertyCheckDialog)

    def retranslateUi(self, FmpSectionPropertyCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        FmpSectionPropertyCheckDialog.setWindowTitle(_translate("FmpSectionPropertyCheckDialog", "Check FMP Model Conveyance"))
        self.label.setText(_translate("FmpSectionPropertyCheckDialog", "FMP .dat File"))
        self.datFileWidget.setFilter(_translate("FmpSectionPropertyCheckDialog", "*.dat"))
        self.datFileReloadBtn.setText(_translate("FmpSectionPropertyCheckDialog", "Reload"))
        self.label_3.setText(_translate("FmpSectionPropertyCheckDialog", "TUFLOW nodes layer"))
        self.conveyanceGroupBox.setTitle(_translate("FmpSectionPropertyCheckDialog", "Conveyance"))
        self.label_2.setText(_translate("FmpSectionPropertyCheckDialog", "K Tolerance"))
        self.kTolSpinbox.setSuffix(_translate("FmpSectionPropertyCheckDialog", " m3/s"))
        item = self.negativeConveyanceTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Node Name"))
        item = self.negativeConveyanceTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Max Negative K value"))
        item = self.negativeConveyanceTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "At Depth"))
        self.groupBox.setTitle(_translate("FmpSectionPropertyCheckDialog", "Banktop Check"))
        self.label_4.setText(_translate("FmpSectionPropertyCheckDialog", "dy Tolerance"))
        self.bankDyToleranceSpinbox.setSuffix(_translate("FmpSectionPropertyCheckDialog", " m"))
        item = self.banktopCheckTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Node Name"))
        item = self.banktopCheckTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Left Bank"))
        item = self.banktopCheckTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Right Bank"))

from qgsdoublespinbox import QgsDoubleSpinBox
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
