# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_fmpstability_check_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FmpStabilityCheckDialog(object):
    def setupUi(self, FmpStabilityCheckDialog):
        FmpStabilityCheckDialog.setObjectName("FmpStabilityCheckDialog")
        FmpStabilityCheckDialog.resize(1053, 749)
        self.verticalLayout = QtWidgets.QVBoxLayout(FmpStabilityCheckDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileSelectionTabWidget = QtWidgets.QTabWidget(FmpStabilityCheckDialog)
        self.fileSelectionTabWidget.setObjectName("fileSelectionTabWidget")
        self.datAndResultsTab = QtWidgets.QWidget()
        self.datAndResultsTab.setObjectName("datAndResultsTab")
        self.gridLayout = QtWidgets.QGridLayout(self.datAndResultsTab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.datAndResultsTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.datFileWidget = QgsFileWidget(self.datAndResultsTab)
        self.datFileWidget.setObjectName("datFileWidget")
        self.gridLayout.addWidget(self.datFileWidget, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.datAndResultsTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.datResultsFileWidget = QgsFileWidget(self.datAndResultsTab)
        self.datResultsFileWidget.setObjectName("datResultsFileWidget")
        self.gridLayout.addWidget(self.datResultsFileWidget, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.datAndResultsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.datTabularCsvFileWidget = QgsFileWidget(self.datAndResultsTab)
        self.datTabularCsvFileWidget.setObjectName("datTabularCsvFileWidget")
        self.gridLayout.addWidget(self.datTabularCsvFileWidget, 2, 1, 1, 1)
        self.reloadDatAndResultsBtn = QtWidgets.QPushButton(self.datAndResultsTab)
        self.reloadDatAndResultsBtn.setObjectName("reloadDatAndResultsBtn")
        self.gridLayout.addWidget(self.reloadDatAndResultsBtn, 3, 0, 1, 1)
        self.fileSelectionTabWidget.addTab(self.datAndResultsTab, "")
        self.existingResultsTab = QtWidgets.QWidget()
        self.existingResultsTab.setObjectName("existingResultsTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.existingResultsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.existingResultsTab)
        self.label_7.setEnabled(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.existingResultsDatFileWidget = QgsFileWidget(self.existingResultsTab)
        self.existingResultsDatFileWidget.setEnabled(True)
        self.existingResultsDatFileWidget.setObjectName("existingResultsDatFileWidget")
        self.gridLayout_2.addWidget(self.existingResultsDatFileWidget, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.existingResultsTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.stageResultsFileWidget = QgsFileWidget(self.existingResultsTab)
        self.stageResultsFileWidget.setObjectName("stageResultsFileWidget")
        self.gridLayout_2.addWidget(self.stageResultsFileWidget, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.existingResultsTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.flowResultsFileWidget = QgsFileWidget(self.existingResultsTab)
        self.flowResultsFileWidget.setObjectName("flowResultsFileWidget")
        self.gridLayout_2.addWidget(self.flowResultsFileWidget, 2, 1, 1, 1)
        self.loadExistingResultsBtn = QtWidgets.QPushButton(self.existingResultsTab)
        self.loadExistingResultsBtn.setObjectName("loadExistingResultsBtn")
        self.gridLayout_2.addWidget(self.loadExistingResultsBtn, 3, 0, 1, 1)
        self.fileSelectionTabWidget.addTab(self.existingResultsTab, "")
        self.verticalLayout.addWidget(self.fileSelectionTabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.validationSeriesCbox = QtWidgets.QComboBox(FmpStabilityCheckDialog)
        self.validationSeriesCbox.setObjectName("validationSeriesCbox")
        self.validationSeriesCbox.addItem("")
        self.validationSeriesCbox.addItem("")
        self.horizontalLayout.addWidget(self.validationSeriesCbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.timestepValueLabel = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.timestepValueLabel.setText("")
        self.timestepValueLabel.setObjectName("timestepValueLabel")
        self.horizontalLayout.addWidget(self.timestepValueLabel)
        self.timestepSlider = QtWidgets.QSlider(FmpStabilityCheckDialog)
        self.timestepSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timestepSlider.setObjectName("timestepSlider")
        self.horizontalLayout.addWidget(self.timestepSlider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.nodeNameLabel = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.nodeNameLabel.setObjectName("nodeNameLabel")
        self.verticalLayout_2.addWidget(self.nodeNameLabel)
        self.line = QtWidgets.QFrame(FmpStabilityCheckDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_8 = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.failedSeriesList = QtWidgets.QListWidget(FmpStabilityCheckDialog)
        self.failedSeriesList.setObjectName("failedSeriesList")
        self.verticalLayout_2.addWidget(self.failedSeriesList)
        self.label_9 = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.allSeriesList = QtWidgets.QListWidget(FmpStabilityCheckDialog)
        self.allSeriesList.setObjectName("allSeriesList")
        self.verticalLayout_2.addWidget(self.allSeriesList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.widget = QtWidgets.QWidget(FmpStabilityCheckDialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.graphLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.graphLayout.setContentsMargins(0, 0, 0, 0)
        self.graphLayout.setObjectName("graphLayout")
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.geomGraphLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.geomGraphLayout.setContentsMargins(0, 0, 0, 0)
        self.geomGraphLayout.setObjectName("geomGraphLayout")
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statusLabel = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_3.addWidget(self.statusLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(FmpStabilityCheckDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(2, 8)

        self.retranslateUi(FmpStabilityCheckDialog)
        self.fileSelectionTabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(FmpStabilityCheckDialog.accept)
        self.buttonBox.rejected.connect(FmpStabilityCheckDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FmpStabilityCheckDialog)

    def retranslateUi(self, FmpStabilityCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        FmpStabilityCheckDialog.setWindowTitle(_translate("FmpStabilityCheckDialog", "FMP Stability Check"))
        self.label_2.setText(_translate("FmpStabilityCheckDialog", "FMP .dat file"))
        self.datFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.dat"))
        self.label_3.setText(_translate("FmpStabilityCheckDialog", "FMP .zzn results"))
        self.datResultsFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.zzn"))
        self.label_4.setText(_translate("FmpStabilityCheckDialog", "TabuleCSV.exe"))
        self.datTabularCsvFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.exe"))
        self.reloadDatAndResultsBtn.setText(_translate("FmpStabilityCheckDialog", "Load Results"))
        self.fileSelectionTabWidget.setTabText(self.fileSelectionTabWidget.indexOf(self.datAndResultsTab), _translate("FmpStabilityCheckDialog", "Dat and Results"))
        self.label_7.setText(_translate("FmpStabilityCheckDialog", "FMP .dat file (optional)"))
        self.existingResultsDatFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.dat"))
        self.label_5.setText(_translate("FmpStabilityCheckDialog", "Stage Results"))
        self.stageResultsFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.csv"))
        self.label_6.setText(_translate("FmpStabilityCheckDialog", "Flow Results"))
        self.flowResultsFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.csv"))
        self.loadExistingResultsBtn.setText(_translate("FmpStabilityCheckDialog", "Load Results"))
        self.fileSelectionTabWidget.setTabText(self.fileSelectionTabWidget.indexOf(self.existingResultsTab), _translate("FmpStabilityCheckDialog", "Existing Results"))
        self.label.setText(_translate("FmpStabilityCheckDialog", "Validation series"))
        self.validationSeriesCbox.setItemText(0, _translate("FmpStabilityCheckDialog", "Stage"))
        self.validationSeriesCbox.setItemText(1, _translate("FmpStabilityCheckDialog", "Flow"))
        self.label_10.setText(_translate("FmpStabilityCheckDialog", "Timestep"))
        self.label_11.setText(_translate("FmpStabilityCheckDialog", "Selected Node:"))
        self.nodeNameLabel.setText(_translate("FmpStabilityCheckDialog", "None"))
        self.label_8.setText(_translate("FmpStabilityCheckDialog", "Failed Sections"))
        self.label_9.setText(_translate("FmpStabilityCheckDialog", "All Sections"))

from qgsfilewidget import QgsFileWidget
