# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_tuflowstability_check_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TuflowStabilityCheckDialog(object):
    def setupUi(self, TuflowStabilityCheckDialog):
        TuflowStabilityCheckDialog.setObjectName("TuflowStabilityCheckDialog")
        TuflowStabilityCheckDialog.resize(1111, 661)
        self.verticalLayout = QtWidgets.QVBoxLayout(TuflowStabilityCheckDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(TuflowStabilityCheckDialog)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.summaryTab = QtWidgets.QWidget()
        self.summaryTab.setObjectName("summaryTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.summaryTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.summaryTab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mbFolderWidget = QgsFileWidget(self.summaryTab)
        self.mbFolderWidget.setObjectName("mbFolderWidget")
        self.horizontalLayout.addWidget(self.mbFolderWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reloadSummaryBtn = QtWidgets.QPushButton(self.summaryTab)
        self.reloadSummaryBtn.setObjectName("reloadSummaryBtn")
        self.horizontalLayout_4.addWidget(self.reloadSummaryBtn)
        self.MBCheckbox = QtWidgets.QCheckBox(self.summaryTab)
        self.MBCheckbox.setChecked(True)
        self.MBCheckbox.setObjectName("MBCheckbox")
        self.horizontalLayout_4.addWidget(self.MBCheckbox)
        self.MB2DCheckbox = QtWidgets.QCheckBox(self.summaryTab)
        self.MB2DCheckbox.setObjectName("MB2DCheckbox")
        self.horizontalLayout_4.addWidget(self.MB2DCheckbox)
        self.MB1DCheckbox = QtWidgets.QCheckBox(self.summaryTab)
        self.MB1DCheckbox.setObjectName("MB1DCheckbox")
        self.horizontalLayout_4.addWidget(self.MB1DCheckbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.summaryTable = QtWidgets.QTableWidget(self.summaryTab)
        self.summaryTable.setObjectName("summaryTable")
        self.summaryTable.setColumnCount(5)
        self.summaryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.summaryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.summaryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.summaryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.summaryTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.summaryTable.setHorizontalHeaderItem(4, item)
        self.summaryTable.horizontalHeader().setCascadingSectionResizes(False)
        self.summaryTable.horizontalHeader().setDefaultSectionSize(200)
        self.summaryTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.summaryTable)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.summaryGraphicsView = QtWidgets.QGraphicsView(self.summaryTab)
        self.summaryGraphicsView.setObjectName("summaryGraphicsView")
        self.horizontalLayout_5.addWidget(self.summaryGraphicsView)
        self.horizontalLayout_5.setStretch(0, 4)
        self.horizontalLayout_5.setStretch(1, 6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.mainTabWidget.addTab(self.summaryTab, "")
        self.individualTab = QtWidgets.QWidget()
        self.individualTab.setObjectName("individualTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.individualTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.individualTab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.mbFileWidget = QgsFileWidget(self.individualTab)
        self.mbFileWidget.setObjectName("mbFileWidget")
        self.horizontalLayout_2.addWidget(self.mbFileWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.reloadIndividualBtn = QtWidgets.QPushButton(self.individualTab)
        self.reloadIndividualBtn.setObjectName("reloadIndividualBtn")
        self.horizontalLayout_6.addWidget(self.reloadIndividualBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.individualSeriesTabWidget = QtWidgets.QTabWidget(self.individualTab)
        self.individualSeriesTabWidget.setObjectName("individualSeriesTabWidget")
        self.presetSeriesTab = QtWidgets.QWidget()
        self.presetSeriesTab.setObjectName("presetSeriesTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.presetSeriesTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mbAndDvolRadioBtn = QtWidgets.QRadioButton(self.presetSeriesTab)
        self.mbAndDvolRadioBtn.setChecked(True)
        self.mbAndDvolRadioBtn.setAutoRepeatDelay(150)
        self.mbAndDvolRadioBtn.setObjectName("mbAndDvolRadioBtn")
        self.verticalLayout_6.addWidget(self.mbAndDvolRadioBtn)
        self.volumesRadioBtn = QtWidgets.QRadioButton(self.presetSeriesTab)
        self.volumesRadioBtn.setObjectName("volumesRadioBtn")
        self.verticalLayout_6.addWidget(self.volumesRadioBtn)
        self.massErrorsRadioBtn = QtWidgets.QRadioButton(self.presetSeriesTab)
        self.massErrorsRadioBtn.setObjectName("massErrorsRadioBtn")
        self.verticalLayout_6.addWidget(self.massErrorsRadioBtn)
        self.volumeErrorsRadioBtn = QtWidgets.QRadioButton(self.presetSeriesTab)
        self.volumeErrorsRadioBtn.setObjectName("volumeErrorsRadioBtn")
        self.verticalLayout_6.addWidget(self.volumeErrorsRadioBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.individualSeriesTabWidget.addTab(self.presetSeriesTab, "")
        self.customSeriesTab = QtWidgets.QWidget()
        self.customSeriesTab.setObjectName("customSeriesTab")
        self.individualSeriesTabWidget.addTab(self.customSeriesTab, "")
        self.verticalLayout_7.addWidget(self.individualSeriesTabWidget)
        self.individualUpdateGraphBtn = QtWidgets.QPushButton(self.individualTab)
        self.individualUpdateGraphBtn.setObjectName("individualUpdateGraphBtn")
        self.verticalLayout_7.addWidget(self.individualUpdateGraphBtn)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.individualGraphicsView = QtWidgets.QGraphicsView(self.individualTab)
        self.individualGraphicsView.setObjectName("individualGraphicsView")
        self.horizontalLayout_3.addWidget(self.individualGraphicsView)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.mainTabWidget.addTab(self.individualTab, "")
        self.verticalLayout.addWidget(self.mainTabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(TuflowStabilityCheckDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TuflowStabilityCheckDialog)
        self.mainTabWidget.setCurrentIndex(0)
        self.individualSeriesTabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(TuflowStabilityCheckDialog.accept)
        self.buttonBox.rejected.connect(TuflowStabilityCheckDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TuflowStabilityCheckDialog)

    def retranslateUi(self, TuflowStabilityCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        TuflowStabilityCheckDialog.setWindowTitle(_translate("TuflowStabilityCheckDialog", "TUFLOW Stability Viewer"))
        self.label.setText(_translate("TuflowStabilityCheckDialog", "TUFLOW MB folder"))
        self.mbFolderWidget.setFilter(_translate("TuflowStabilityCheckDialog", "*.csv"))
        self.reloadSummaryBtn.setText(_translate("TuflowStabilityCheckDialog", "Reload"))
        self.MBCheckbox.setText(_translate("TuflowStabilityCheckDialog", "_MB"))
        self.MB2DCheckbox.setText(_translate("TuflowStabilityCheckDialog", "_MB2D"))
        self.MB1DCheckbox.setText(_translate("TuflowStabilityCheckDialog", "_MB1D"))
        item = self.summaryTable.horizontalHeaderItem(0)
        item.setText(_translate("TuflowStabilityCheckDialog", "Graph"))
        item = self.summaryTable.horizontalHeaderItem(1)
        item.setText(_translate("TuflowStabilityCheckDialog", "Failed"))
        item = self.summaryTable.horizontalHeaderItem(2)
        item.setText(_translate("TuflowStabilityCheckDialog", "Max"))
        item = self.summaryTable.horizontalHeaderItem(3)
        item.setText(_translate("TuflowStabilityCheckDialog", "Run Name"))
        item = self.summaryTable.horizontalHeaderItem(4)
        item.setText(_translate("TuflowStabilityCheckDialog", "Full Path"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.summaryTab), _translate("TuflowStabilityCheckDialog", "Summary"))
        self.label_2.setText(_translate("TuflowStabilityCheckDialog", "TUFLOW MB file"))
        self.mbFileWidget.setFilter(_translate("TuflowStabilityCheckDialog", "*.csv"))
        self.reloadIndividualBtn.setText(_translate("TuflowStabilityCheckDialog", "Reload"))
        self.mbAndDvolRadioBtn.setText(_translate("TuflowStabilityCheckDialog", "MB and dVol"))
        self.volumesRadioBtn.setText(_translate("TuflowStabilityCheckDialog", "Volumes"))
        self.massErrorsRadioBtn.setText(_translate("TuflowStabilityCheckDialog", "Mass Errors"))
        self.volumeErrorsRadioBtn.setText(_translate("TuflowStabilityCheckDialog", "Volume Errors"))
        self.individualSeriesTabWidget.setTabText(self.individualSeriesTabWidget.indexOf(self.presetSeriesTab), _translate("TuflowStabilityCheckDialog", "Presets"))
        self.individualSeriesTabWidget.setTabText(self.individualSeriesTabWidget.indexOf(self.customSeriesTab), _translate("TuflowStabilityCheckDialog", "Custom"))
        self.individualUpdateGraphBtn.setText(_translate("TuflowStabilityCheckDialog", "Update Graph"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.individualTab), _translate("TuflowStabilityCheckDialog", "Individual"))

from qgsfilewidget import QgsFileWidget
