# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ModelReviewTools
                                 A QGIS plugin
 A collection of tools for reviewing hydraulic models
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-23
        copyright            : (C) 2021 by Duncan Runnacles
        email                : info@ermeviewenvironmental.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

from qgis.PyQt.QtCore import *
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtWidgets import *
from qgis.core import *

from builtins import IOError

ICON_NAME = 'icon.png'
MENU_NAME = 'ModCheck'
TR_MENU_NAME = '&ModCheck'
SHIP_VERSION = 'ship-0.3.3.dev0-py3.8.egg'

# Make sure we have access to the SHIP library
ship_path = os.path.join(os.path.dirname(__file__), 'dependencies', SHIP_VERSION)
try:
    sys.path.append(ship_path)
    import ship
except ImportError:
    raise ('Unable to load SHIP library')
from .dialogs import *

class Menu:

    def __init__(self, iface):
        
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)


        # Declare instance attributes
        #000  self.actions = []
        #self.menu = self.tr(u'&ModCheck')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        #self.first_start = None
        
    
    def initGui(self):
        self.dir = os.path.dirname(__file__)
        self.icon_dir = self.dir
        icon = QIcon(os.path.join(self.icon_dir, "icon.png"))
        self.nrfa_dialog = None
        self.chainage_dialog = None
        self.fmpwidth_dialog = None

        # submenu example: Chainage submenu
#         self.chainage_menu = QMenu(QCoreApplication.translate("ModCheck", "&Chainage"))
#         self.iface.addPluginToMenu("&ModCheck", self.chainage_menu.menuAction())
#         self.calc_fmp_chainage_action = QAction(icon, "Calculate FMP Chainage", self.iface.mainWindow())
#         self.calc_fmp_chainage_action.triggered.connect(self.calc_fmp_chainage)
#         self.chainage_menu.addAction(self.calc_fmp_chainage_action)
        # unloading the menu item (put in unload)
#         self.iface.removePluginMenu("&ModCheck", self.chainage_menu.menuAction())

        # Chainage / node distance check
        self.check_fmptuflow_chainage_action = QAction(icon, "Check FMP-TUFLOW Chainage", self.iface.mainWindow())
        self.check_fmptuflow_chainage_action.triggered.connect(self.check_fmptuflow_chainage)
        self.iface.addPluginToMenu("&ModCheck", self.check_fmptuflow_chainage_action)
        
        # 1D2D width check
        self.check_1d2dWidth_action = QAction(icon, "Check 1D-2D width", self.iface.mainWindow())
        self.check_1d2dWidth_action.triggered.connect(self.check_1d2d_width)
        self.iface.addPluginToMenu("&ModCheck", self.check_1d2dWidth_action)

        # FMP / TUFLOW default variables check
        self.get_runsummary_action = QAction(icon, "Run variables and summary", self.iface.mainWindow())
        self.get_runsummary_action.triggered.connect(self.get_runsummary)
        self.iface.addPluginToMenu("&ModCheck", self.get_runsummary_action)
        
        # FMP section property check
        self.check_fmpsections_action = QAction(icon, "Check FMP section properties", self.iface.mainWindow())
        self.check_fmpsections_action.triggered.connect(self.check_fmp_sections)
        self.iface.addPluginToMenu("&ModCheck", self.check_fmpsections_action)
        
        # FMP REFH unit compare
        self.check_fmprefh_action = QAction(icon, "Compare FMP refh units", self.iface.mainWindow())
        self.check_fmprefh_action.triggered.connect(self.check_fmp_refh)
        self.iface.addPluginToMenu("&ModCheck", self.check_fmprefh_action)
        
        # TUFLOW stability outputs viewer (MB, Dvol, etc)
        self.check_tuflowstability_action = QAction(icon, "Check TUFLOW MB", self.iface.mainWindow())
        self.check_tuflowstability_action.triggered.connect(self.check_tuflow_stability)
        self.iface.addPluginToMenu("&ModCheck", self.check_tuflowstability_action)

        # NRFA Station viewer
        self.nrfa_stationviewer_action = QAction(icon, "View NRFA Station Info", self.iface.mainWindow())
        self.nrfa_stationviewer_action.triggered.connect(self.view_nrfa_station)
        self.iface.addPluginToMenu("&ModCheck", self.nrfa_stationviewer_action)
        
    def unload(self):
        self.iface.removePluginMenu("&ModCheck", self.check_fmptuflow_chainage_action)
        self.iface.removePluginMenu("&ModCheck", self.check_1d2dWidth_action)
        self.iface.removePluginMenu("&ModCheck", self.get_runsummary_action)
        self.iface.removePluginMenu("&ModCheck", self.check_fmpsections_action)
        self.iface.removePluginMenu("&ModCheck", self.check_fmprefh_action)
        self.iface.removePluginMenu("&ModCheck", self.check_tuflowstability_action)
        self.iface.removePluginMenu("&ModCheck", self.nrfa_stationviewer_action)
        
    def check_fmptuflow_chainage(self):
        if self.chainage_dialog is None:
            self.chainage_dialog = ChainageCalculatorDialog(self.iface, QgsProject.instance())
            self.chainage_dialog.closing.connect(self._chainage_dialog_close)
            self.chainage_dialog.show()
        else:
            self.chainage_dialog.setWindowState(self.chainage_dialog.windowState() & ~Qt.WindowMinimized | Qt.WindowActive)

    def _chainage_dialog_close(self):
        self.chainage_dialog = None
        
    def check_1d2d_width(self):
#         dialog = FmpTuflowWidthCheckDialog(self.iface, QgsProject.instance())
#         dialog.exec_()
        if self.fmpwidth_dialog is None:
            self.fmpwidth_dialog = FmpTuflowWidthCheckDialog(self.iface, QgsProject.instance())
            self.fmpwidth_dialog.closing.connect(self._fmpwidth_dialog_close)
            self.fmpwidth_dialog.show()
        else:
            self.fmpwidth_dialog.setWindowState(self.fmpwidth_dialog.windowState() & ~Qt.WindowMinimized | Qt.WindowActive)

    def _fmpwidth_dialog_close(self):
        self.fmpwidth_dialog = None
        
    def get_runsummary(self):
        dialog = FmpTuflowVariablesCheckDialog(self.iface, QgsProject.instance())
        dialog.exec_()
        
    def check_fmp_sections(self):
        dialog = FmpSectionCheckDialog(self.iface, QgsProject.instance())
        dialog.exec_()

    def check_fmp_refh(self):
        dialog = FmpRefhCheckDialog(self.iface, QgsProject.instance())
        dialog.exec_()
        
    def check_tuflow_stability(self): 
        dialog = TuflowStabilityCheckDialog(self.iface, QgsProject.instance())
        dialog.exec_()

    def view_nrfa_station(self): 
        if self.nrfa_dialog is None:
            self.nrfa_dialog = NrfaStationViewerDialog(self.iface, QgsProject.instance())
            self.nrfa_dialog.closing.connect(self._nrfa_dialog_close)
            self.nrfa_dialog.show()
        else:
            self.nrfa_dialog.setWindowState(self.nrfa_dialog.windowState() & ~Qt.WindowMinimized | Qt.WindowActive)
        
    def _nrfa_dialog_close(self):
        self.nrfa_dialog = None
        
        
        
        
        
        
        