# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_chainage_calculator_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChainageCalculator(object):
    def setupUi(self, ChainageCalculator):
        ChainageCalculator.setObjectName("ChainageCalculator")
        ChainageCalculator.resize(560, 474)
        self.gridLayout = QtWidgets.QGridLayout(ChainageCalculator)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(ChainageCalculator)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.workingDirFileWidget = QgsFileWidget(self.groupBox)
        self.workingDirFileWidget.setFilter("")
        self.workingDirFileWidget.setStorageMode(QgsFileWidget.GetDirectory)
        self.workingDirFileWidget.setOptions(QtWidgets.QFileDialog.ShowDirsOnly)
        self.workingDirFileWidget.setObjectName("workingDirFileWidget")
        self.verticalLayout.addWidget(self.workingDirFileWidget)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.datFileWidget = QgsFileWidget(self.groupBox)
        self.datFileWidget.setObjectName("datFileWidget")
        self.verticalLayout.addWidget(self.datFileWidget)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 2)
        self.tuflowInputsGroupbox = QtWidgets.QGroupBox(ChainageCalculator)
        self.tuflowInputsGroupbox.setObjectName("tuflowInputsGroupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tuflowInputsGroupbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 5, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tuflowInputsGroupbox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 3)
        self.compareChainageBtn = QtWidgets.QPushButton(self.tuflowInputsGroupbox)
        self.compareChainageBtn.setObjectName("compareChainageBtn")
        self.gridLayout_3.addWidget(self.compareChainageBtn, 5, 0, 1, 1)
        self.dxToleranceSpinbox = QgsSpinBox(self.tuflowInputsGroupbox)
        self.dxToleranceSpinbox.setMaximum(50)
        self.dxToleranceSpinbox.setProperty("value", 10)
        self.dxToleranceSpinbox.setObjectName("dxToleranceSpinbox")
        self.gridLayout_3.addWidget(self.dxToleranceSpinbox, 5, 5, 1, 1)
        self.estryNwkLayerCBox = QgsMapLayerComboBox(self.tuflowInputsGroupbox)
        self.estryNwkLayerCBox.setObjectName("estryNwkLayerCBox")
        self.gridLayout_3.addWidget(self.estryNwkLayerCBox, 1, 0, 1, 6)
        self.label_5 = QtWidgets.QLabel(self.tuflowInputsGroupbox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 5, 1, 1)
        self.gridLayout.addWidget(self.tuflowInputsGroupbox, 6, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(ChainageCalculator)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fmpOnlyCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.fmpOnlyCheckbox.setMaximumSize(QtCore.QSize(276, 16777215))
        self.fmpOnlyCheckbox.setObjectName("fmpOnlyCheckbox")
        self.verticalLayout_2.addWidget(self.fmpOnlyCheckbox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calcFmpChainageOnlyBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.calcFmpChainageOnlyBtn.setEnabled(False)
        self.calcFmpChainageOnlyBtn.setObjectName("calcFmpChainageOnlyBtn")
        self.horizontalLayout.addWidget(self.calcFmpChainageOnlyBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(ChainageCalculator)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(ChainageCalculator)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loggingTextedit = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.loggingTextedit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.loggingTextedit.setObjectName("loggingTextedit")
        self.verticalLayout_3.addWidget(self.loggingTextedit)
        self.gridLayout.addWidget(self.groupBox_4, 8, 0, 1, 2)

        self.retranslateUi(ChainageCalculator)
        self.buttonBox.accepted.connect(ChainageCalculator.accept)
        self.buttonBox.rejected.connect(ChainageCalculator.reject)
        QtCore.QMetaObject.connectSlotsByName(ChainageCalculator)

    def retranslateUi(self, ChainageCalculator):
        _translate = QtCore.QCoreApplication.translate
        ChainageCalculator.setWindowTitle(_translate("ChainageCalculator", "FMP-TUFLOW Chainage Compare"))
        self.groupBox.setTitle(_translate("ChainageCalculator", "Input Files"))
        self.label.setText(_translate("ChainageCalculator", "Set output folder"))
        self.workingDirFileWidget.setDialogTitle(_translate("ChainageCalculator", "Select output folder"))
        self.label_2.setText(_translate("ChainageCalculator", "FMP .dat file"))
        self.datFileWidget.setDialogTitle(_translate("ChainageCalculator", "Load chainage results file ..."))
        self.datFileWidget.setFilter(_translate("ChainageCalculator", "*.dat"))
        self.tuflowInputsGroupbox.setTitle(_translate("ChainageCalculator", "TUFLOW inputs"))
        self.label_3.setText(_translate("ChainageCalculator", "Nwk line layer"))
        self.compareChainageBtn.setText(_translate("ChainageCalculator", "Compare TUFLOW / FMP Chainage"))
        self.dxToleranceSpinbox.setSuffix(_translate("ChainageCalculator", " m"))
        self.label_5.setText(_translate("ChainageCalculator", "DX Tolerance (m)"))
        self.groupBox_2.setTitle(_translate("ChainageCalculator", "FMP Only?"))
        self.fmpOnlyCheckbox.setText(_translate("ChainageCalculator", "Calculate FMP chainage only"))
        self.calcFmpChainageOnlyBtn.setText(_translate("ChainageCalculator", "Calculate FMP Chainage"))
        self.groupBox_4.setTitle(_translate("ChainageCalculator", "Outputs"))

from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
from qgsspinbox import QgsSpinBox
