# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_fmpstability_check_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FmpStabilityCheckDialog(object):
    def setupUi(self, FmpStabilityCheckDialog):
        FmpStabilityCheckDialog.setObjectName("FmpStabilityCheckDialog")
        FmpStabilityCheckDialog.resize(1053, 749)
        self.verticalLayout = QtWidgets.QVBoxLayout(FmpStabilityCheckDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileSelectionTabWidget = QtWidgets.QTabWidget(FmpStabilityCheckDialog)
        self.fileSelectionTabWidget.setObjectName("fileSelectionTabWidget")
        self.datAndResultsTab = QtWidgets.QWidget()
        self.datAndResultsTab.setObjectName("datAndResultsTab")
        self.gridLayout = QtWidgets.QGridLayout(self.datAndResultsTab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.datAndResultsTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.datFileWidget = QgsFileWidget(self.datAndResultsTab)
        self.datFileWidget.setObjectName("datFileWidget")
        self.gridLayout.addWidget(self.datFileWidget, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.datAndResultsTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.datResultsFileWidget = QgsFileWidget(self.datAndResultsTab)
        self.datResultsFileWidget.setObjectName("datResultsFileWidget")
        self.gridLayout.addWidget(self.datResultsFileWidget, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.datAndResultsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.datTabularCsvFileWidget = QgsFileWidget(self.datAndResultsTab)
        self.datTabularCsvFileWidget.setObjectName("datTabularCsvFileWidget")
        self.gridLayout.addWidget(self.datTabularCsvFileWidget, 2, 1, 1, 1)
        self.reloadDatAndResultsBtn = QtWidgets.QPushButton(self.datAndResultsTab)
        self.reloadDatAndResultsBtn.setObjectName("reloadDatAndResultsBtn")
        self.gridLayout.addWidget(self.reloadDatAndResultsBtn, 3, 0, 1, 1)
        self.fileSelectionTabWidget.addTab(self.datAndResultsTab, "")
        self.existingResultsTab = QtWidgets.QWidget()
        self.existingResultsTab.setObjectName("existingResultsTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.existingResultsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.existingResultsTab)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.existingResultsDatFileWidget = QgsFileWidget(self.existingResultsTab)
        self.existingResultsDatFileWidget.setEnabled(False)
        self.existingResultsDatFileWidget.setObjectName("existingResultsDatFileWidget")
        self.gridLayout_2.addWidget(self.existingResultsDatFileWidget, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.existingResultsTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.stageResultsFileWidget = QgsFileWidget(self.existingResultsTab)
        self.stageResultsFileWidget.setObjectName("stageResultsFileWidget")
        self.gridLayout_2.addWidget(self.stageResultsFileWidget, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.existingResultsTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.flowResultsFileWidget = QgsFileWidget(self.existingResultsTab)
        self.flowResultsFileWidget.setObjectName("flowResultsFileWidget")
        self.gridLayout_2.addWidget(self.flowResultsFileWidget, 2, 1, 1, 1)
        self.loadExistingResultsBtn = QtWidgets.QPushButton(self.existingResultsTab)
        self.loadExistingResultsBtn.setObjectName("loadExistingResultsBtn")
        self.gridLayout_2.addWidget(self.loadExistingResultsBtn, 3, 0, 1, 1)
        self.fileSelectionTabWidget.addTab(self.existingResultsTab, "")
        self.verticalLayout.addWidget(self.fileSelectionTabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(FmpStabilityCheckDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.validationSeriesCbox = QtWidgets.QComboBox(FmpStabilityCheckDialog)
        self.validationSeriesCbox.setObjectName("validationSeriesCbox")
        self.validationSeriesCbox.addItem("")
        self.validationSeriesCbox.addItem("")
        self.horizontalLayout.addWidget(self.validationSeriesCbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.failedSeriesList = QtWidgets.QListWidget(FmpStabilityCheckDialog)
        self.failedSeriesList.setObjectName("failedSeriesList")
        self.horizontalLayout_2.addWidget(self.failedSeriesList)
        self.allSeriesList = QtWidgets.QListWidget(FmpStabilityCheckDialog)
        self.allSeriesList.setObjectName("allSeriesList")
        self.horizontalLayout_2.addWidget(self.allSeriesList)
        self.graphLayout = QtWidgets.QVBoxLayout()
        self.graphLayout.setObjectName("graphLayout")
        self.horizontalLayout_2.addLayout(self.graphLayout)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(FmpStabilityCheckDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(2, 10)

        self.retranslateUi(FmpStabilityCheckDialog)
        self.fileSelectionTabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(FmpStabilityCheckDialog.accept)
        self.buttonBox.rejected.connect(FmpStabilityCheckDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FmpStabilityCheckDialog)

    def retranslateUi(self, FmpStabilityCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        FmpStabilityCheckDialog.setWindowTitle(_translate("FmpStabilityCheckDialog", "Dialog"))
        self.label_2.setText(_translate("FmpStabilityCheckDialog", "FMP .dat file"))
        self.datFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.dat"))
        self.label_3.setText(_translate("FmpStabilityCheckDialog", "FMP .zzn results"))
        self.datResultsFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.zzn"))
        self.label_4.setText(_translate("FmpStabilityCheckDialog", "TabuleCSV.exe"))
        self.datTabularCsvFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.exe"))
        self.reloadDatAndResultsBtn.setText(_translate("FmpStabilityCheckDialog", "Load Results"))
        self.fileSelectionTabWidget.setTabText(self.fileSelectionTabWidget.indexOf(self.datAndResultsTab), _translate("FmpStabilityCheckDialog", "Dat and Results"))
        self.label_7.setText(_translate("FmpStabilityCheckDialog", "FMP .dat file (optional)"))
        self.existingResultsDatFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.dat"))
        self.label_5.setText(_translate("FmpStabilityCheckDialog", "Stage Results"))
        self.stageResultsFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.csv"))
        self.label_6.setText(_translate("FmpStabilityCheckDialog", "Flow Results"))
        self.flowResultsFileWidget.setFilter(_translate("FmpStabilityCheckDialog", "*.csv"))
        self.loadExistingResultsBtn.setText(_translate("FmpStabilityCheckDialog", "Load Results"))
        self.fileSelectionTabWidget.setTabText(self.fileSelectionTabWidget.indexOf(self.existingResultsTab), _translate("FmpStabilityCheckDialog", "Existing Results"))
        self.label.setText(_translate("FmpStabilityCheckDialog", "Validation series"))
        self.validationSeriesCbox.setItemText(0, _translate("FmpStabilityCheckDialog", "Stage"))
        self.validationSeriesCbox.setItemText(1, _translate("FmpStabilityCheckDialog", "Flow"))

from qgsfilewidget import QgsFileWidget
