# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_fmpsectionproperty_check_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FmpSectionPropertyCheckDialog(object):
    def setupUi(self, FmpSectionPropertyCheckDialog):
        FmpSectionPropertyCheckDialog.setObjectName("FmpSectionPropertyCheckDialog")
        FmpSectionPropertyCheckDialog.resize(1227, 783)
        self.verticalLayout = QtWidgets.QVBoxLayout(FmpSectionPropertyCheckDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(FmpSectionPropertyCheckDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.datFileWidget = QgsFileWidget(FmpSectionPropertyCheckDialog)
        self.datFileWidget.setObjectName("datFileWidget")
        self.horizontalLayout_4.addWidget(self.datFileWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(FmpSectionPropertyCheckDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.fmpNodesLayerCbox = QgsMapLayerComboBox(self.groupBox)
        self.fmpNodesLayerCbox.setObjectName("fmpNodesLayerCbox")
        self.verticalLayout_3.addWidget(self.fmpNodesLayerCbox)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.kTolSpinbox = QgsDoubleSpinBox(self.groupBox)
        self.kTolSpinbox.setMaximum(500.0)
        self.kTolSpinbox.setSingleStep(10.0)
        self.kTolSpinbox.setProperty("value", 10.0)
        self.kTolSpinbox.setObjectName("kTolSpinbox")
        self.horizontalLayout_2.addWidget(self.kTolSpinbox)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.bankDyToleranceSpinbox = QgsDoubleSpinBox(self.groupBox)
        self.bankDyToleranceSpinbox.setMinimum(0.01)
        self.bankDyToleranceSpinbox.setMaximum(1.0)
        self.bankDyToleranceSpinbox.setSingleStep(0.1)
        self.bankDyToleranceSpinbox.setProperty("value", 0.1)
        self.bankDyToleranceSpinbox.setObjectName("bankDyToleranceSpinbox")
        self.horizontalLayout_2.addWidget(self.bankDyToleranceSpinbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.datFileReloadBtn = QtWidgets.QPushButton(self.groupBox)
        self.datFileReloadBtn.setObjectName("datFileReloadBtn")
        self.horizontalLayout.addWidget(self.datFileReloadBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.resultsLayout = QtWidgets.QHBoxLayout()
        self.resultsLayout.setObjectName("resultsLayout")
        self.resultsTabWidget = QtWidgets.QTabWidget(FmpSectionPropertyCheckDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsTabWidget.sizePolicy().hasHeightForWidth())
        self.resultsTabWidget.setSizePolicy(sizePolicy)
        self.resultsTabWidget.setObjectName("resultsTabWidget")
        self.conveyanceTab = QtWidgets.QWidget()
        self.conveyanceTab.setObjectName("conveyanceTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.conveyanceTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.negativeConveyanceTable = QtWidgets.QTableWidget(self.conveyanceTab)
        self.negativeConveyanceTable.setObjectName("negativeConveyanceTable")
        self.negativeConveyanceTable.setColumnCount(3)
        self.negativeConveyanceTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.negativeConveyanceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.negativeConveyanceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.negativeConveyanceTable.setHorizontalHeaderItem(2, item)
        self.negativeConveyanceTable.horizontalHeader().setDefaultSectionSize(120)
        self.negativeConveyanceTable.horizontalHeader().setMinimumSectionSize(120)
        self.negativeConveyanceTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.negativeConveyanceTable)
        self.resultsTabWidget.addTab(self.conveyanceTab, "")
        self.banktopTab = QtWidgets.QWidget()
        self.banktopTab.setObjectName("banktopTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.banktopTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.banktopCheckTable = QtWidgets.QTableWidget(self.banktopTab)
        self.banktopCheckTable.setObjectName("banktopCheckTable")
        self.banktopCheckTable.setColumnCount(3)
        self.banktopCheckTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.banktopCheckTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.banktopCheckTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.banktopCheckTable.setHorizontalHeaderItem(2, item)
        self.banktopCheckTable.horizontalHeader().setDefaultSectionSize(120)
        self.banktopCheckTable.horizontalHeader().setMinimumSectionSize(120)
        self.banktopCheckTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.banktopCheckTable)
        self.resultsTabWidget.addTab(self.banktopTab, "")
        self.resultsLayout.addWidget(self.resultsTabWidget)
        self.graphLayout = QtWidgets.QVBoxLayout()
        self.graphLayout.setObjectName("graphLayout")
        self.resultsLayout.addLayout(self.graphLayout)
        self.resultsLayout.setStretch(0, 4)
        self.resultsLayout.setStretch(1, 6)
        self.verticalLayout.addLayout(self.resultsLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.statusLabel = QtWidgets.QLabel(FmpSectionPropertyCheckDialog)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_5.addWidget(self.statusLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(FmpSectionPropertyCheckDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(FmpSectionPropertyCheckDialog)
        self.resultsTabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(FmpSectionPropertyCheckDialog.accept)
        self.buttonBox.rejected.connect(FmpSectionPropertyCheckDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FmpSectionPropertyCheckDialog)

    def retranslateUi(self, FmpSectionPropertyCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        FmpSectionPropertyCheckDialog.setWindowTitle(_translate("FmpSectionPropertyCheckDialog", "Check FMP Model Sections"))
        self.label.setText(_translate("FmpSectionPropertyCheckDialog", "FMP .dat File"))
        self.datFileWidget.setFilter(_translate("FmpSectionPropertyCheckDialog", "*.dat"))
        self.groupBox.setTitle(_translate("FmpSectionPropertyCheckDialog", "Setup"))
        self.label_3.setText(_translate("FmpSectionPropertyCheckDialog", "TUFLOW nodes layer (only used for locating the section in the nodes layer - right-click table options)"))
        self.label_2.setText(_translate("FmpSectionPropertyCheckDialog", "K Tolerance"))
        self.kTolSpinbox.setSuffix(_translate("FmpSectionPropertyCheckDialog", " m3/s"))
        self.label_4.setText(_translate("FmpSectionPropertyCheckDialog", "dy Tolerance"))
        self.bankDyToleranceSpinbox.setSuffix(_translate("FmpSectionPropertyCheckDialog", " m"))
        self.datFileReloadBtn.setText(_translate("FmpSectionPropertyCheckDialog", "Reload"))
        item = self.negativeConveyanceTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Node Name"))
        item = self.negativeConveyanceTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Max Negative K value"))
        item = self.negativeConveyanceTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "At Depth"))
        self.resultsTabWidget.setTabText(self.resultsTabWidget.indexOf(self.conveyanceTab), _translate("FmpSectionPropertyCheckDialog", "Conveyance"))
        item = self.banktopCheckTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Node Name"))
        item = self.banktopCheckTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Left Bank"))
        item = self.banktopCheckTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpSectionPropertyCheckDialog", "Right Bank"))
        self.resultsTabWidget.setTabText(self.resultsTabWidget.indexOf(self.banktopTab), _translate("FmpSectionPropertyCheckDialog", "Banktops"))

from qgsdoublespinbox import QgsDoubleSpinBox
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
