# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_nrfa_viewer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NrfaViewerDialog(object):
    def setupUi(self, NrfaViewerDialog):
        NrfaViewerDialog.setObjectName("NrfaViewerDialog")
        NrfaViewerDialog.setWindowModality(QtCore.Qt.NonModal)
        NrfaViewerDialog.resize(888, 679)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(NrfaViewerDialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.workingDirGroupbox = QtWidgets.QGroupBox(NrfaViewerDialog)
        self.workingDirGroupbox.setObjectName("workingDirGroupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.workingDirGroupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.workingDirFileWidget = QgsFileWidget(self.workingDirGroupbox)
        self.workingDirFileWidget.setObjectName("workingDirFileWidget")
        self.verticalLayout_2.addWidget(self.workingDirFileWidget)
        self.verticalLayout_5.addWidget(self.workingDirGroupbox)
        self.fetchStationsGroupbox = QtWidgets.QGroupBox(NrfaViewerDialog)
        self.fetchStationsGroupbox.setObjectName("fetchStationsGroupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fetchStationsGroupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.fetchStationsGroupbox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.maxDistanceSpinbox = QgsSpinBox(self.fetchStationsGroupbox)
        self.maxDistanceSpinbox.setEnabled(True)
        self.maxDistanceSpinbox.setMinimum(1)
        self.maxDistanceSpinbox.setMaximum(1000)
        self.maxDistanceSpinbox.setSingleStep(5)
        self.maxDistanceSpinbox.setProperty("value", 15)
        self.maxDistanceSpinbox.setObjectName("maxDistanceSpinbox")
        self.horizontalLayout.addWidget(self.maxDistanceSpinbox)
        self.fetchStationsBtn = QtWidgets.QPushButton(self.fetchStationsGroupbox)
        self.fetchStationsBtn.setObjectName("fetchStationsBtn")
        self.horizontalLayout.addWidget(self.fetchStationsBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.fetchStationsGroupbox)
        self.stationInfoGroupbox = QtWidgets.QGroupBox(NrfaViewerDialog)
        self.stationInfoGroupbox.setEnabled(False)
        self.stationInfoGroupbox.setObjectName("stationInfoGroupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.stationInfoGroupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stationNamesCbox = QtWidgets.QComboBox(self.stationInfoGroupbox)
        self.stationNamesCbox.setMinimumSize(QtCore.QSize(300, 0))
        self.stationNamesCbox.setObjectName("stationNamesCbox")
        self.horizontalLayout_6.addWidget(self.stationNamesCbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.stationTabWidget = QtWidgets.QTabWidget(self.stationInfoGroupbox)
        self.stationTabWidget.setObjectName("stationTabWidget")
        self.overviewTab = QtWidgets.QWidget()
        self.overviewTab.setObjectName("overviewTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.overviewTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stationInfoTextbox = QtWidgets.QTextEdit(self.overviewTab)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.stationInfoTextbox.setFont(font)
        self.stationInfoTextbox.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.stationInfoTextbox.setObjectName("stationInfoTextbox")
        self.verticalLayout.addWidget(self.stationInfoTextbox)
        self.stationTabWidget.addTab(self.overviewTab, "")
        self.fullDetails = QtWidgets.QWidget()
        self.fullDetails.setObjectName("fullDetails")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fullDetails)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fullDetailsTextbox = QtWidgets.QTextEdit(self.fullDetails)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.fullDetailsTextbox.setFont(font)
        self.fullDetailsTextbox.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.fullDetailsTextbox.setObjectName("fullDetailsTextbox")
        self.verticalLayout_6.addWidget(self.fullDetailsTextbox)
        self.stationTabWidget.addTab(self.fullDetails, "")
        self.amaxTab = QtWidgets.QWidget()
        self.amaxTab.setObjectName("amaxTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.amaxTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.amaxSummaryTextbox = QtWidgets.QTextEdit(self.amaxTab)
        self.amaxSummaryTextbox.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.amaxSummaryTextbox.setFont(font)
        self.amaxSummaryTextbox.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.amaxSummaryTextbox.setObjectName("amaxSummaryTextbox")
        self.verticalLayout_7.addWidget(self.amaxSummaryTextbox)
        self.amaxResultsTable = QtWidgets.QTableWidget(self.amaxTab)
        self.amaxResultsTable.setObjectName("amaxResultsTable")
        self.amaxResultsTable.setColumnCount(2)
        self.amaxResultsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.amaxResultsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.amaxResultsTable.setHorizontalHeaderItem(1, item)
        self.amaxResultsTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.amaxResultsTable)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.showAmaxGraphBtn = QtWidgets.QPushButton(self.amaxTab)
        self.showAmaxGraphBtn.setObjectName("showAmaxGraphBtn")
        self.horizontalLayout_2.addWidget(self.showAmaxGraphBtn)
        self.exportAmaxCsvBtn = QtWidgets.QPushButton(self.amaxTab)
        self.exportAmaxCsvBtn.setObjectName("exportAmaxCsvBtn")
        self.horizontalLayout_2.addWidget(self.exportAmaxCsvBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.stationTabWidget.addTab(self.amaxTab, "")
        self.potTab = QtWidgets.QWidget()
        self.potTab.setObjectName("potTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.potTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.potSummaryTextbox = QtWidgets.QTextEdit(self.potTab)
        self.potSummaryTextbox.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.potSummaryTextbox.setFont(font)
        self.potSummaryTextbox.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.potSummaryTextbox.setObjectName("potSummaryTextbox")
        self.verticalLayout_9.addWidget(self.potSummaryTextbox)
        self.potResultsTable = QtWidgets.QTableWidget(self.potTab)
        self.potResultsTable.setObjectName("potResultsTable")
        self.potResultsTable.setColumnCount(2)
        self.potResultsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.potResultsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.potResultsTable.setHorizontalHeaderItem(1, item)
        self.potResultsTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.potResultsTable)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.showPotGraphBtn = QtWidgets.QPushButton(self.potTab)
        self.showPotGraphBtn.setObjectName("showPotGraphBtn")
        self.horizontalLayout_5.addWidget(self.showPotGraphBtn)
        self.exportPotCsvBtn = QtWidgets.QPushButton(self.potTab)
        self.exportPotCsvBtn.setObjectName("exportPotCsvBtn")
        self.horizontalLayout_5.addWidget(self.exportPotCsvBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.stationTabWidget.addTab(self.potTab, "")
        self.dailyFlowsTab = QtWidgets.QWidget()
        self.dailyFlowsTab.setObjectName("dailyFlowsTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dailyFlowsTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.dailyFlowsTab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dailyFlowsYearCbox = QtWidgets.QComboBox(self.dailyFlowsTab)
        self.dailyFlowsYearCbox.setMinimumSize(QtCore.QSize(150, 0))
        self.dailyFlowsYearCbox.setObjectName("dailyFlowsYearCbox")
        self.horizontalLayout_3.addWidget(self.dailyFlowsYearCbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.dailyFlowsTable = QtWidgets.QTableWidget(self.dailyFlowsTab)
        self.dailyFlowsTable.setObjectName("dailyFlowsTable")
        self.dailyFlowsTable.setColumnCount(4)
        self.dailyFlowsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dailyFlowsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyFlowsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyFlowsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dailyFlowsTable.setHorizontalHeaderItem(3, item)
        self.dailyFlowsTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.dailyFlowsTable)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.showDailyFlowsGraphBtn = QtWidgets.QPushButton(self.dailyFlowsTab)
        self.showDailyFlowsGraphBtn.setObjectName("showDailyFlowsGraphBtn")
        self.horizontalLayout_4.addWidget(self.showDailyFlowsGraphBtn)
        self.exportDailyFlowsCsvBtn = QtWidgets.QPushButton(self.dailyFlowsTab)
        self.exportDailyFlowsCsvBtn.setObjectName("exportDailyFlowsCsvBtn")
        self.horizontalLayout_4.addWidget(self.exportDailyFlowsCsvBtn)
        self.dailyFlowExportTypeCbox = QtWidgets.QComboBox(self.dailyFlowsTab)
        self.dailyFlowExportTypeCbox.setMinimumSize(QtCore.QSize(200, 0))
        self.dailyFlowExportTypeCbox.setObjectName("dailyFlowExportTypeCbox")
        self.dailyFlowExportTypeCbox.addItem("")
        self.dailyFlowExportTypeCbox.addItem("")
        self.horizontalLayout_4.addWidget(self.dailyFlowExportTypeCbox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.stationTabWidget.addTab(self.dailyFlowsTab, "")
        self.verticalLayout_4.addWidget(self.stationTabWidget)
        self.verticalLayout_5.addWidget(self.stationInfoGroupbox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.statusLabel = QtWidgets.QLabel(NrfaViewerDialog)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_7.addWidget(self.statusLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(NrfaViewerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_7.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)

        self.retranslateUi(NrfaViewerDialog)
        self.stationTabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(NrfaViewerDialog.accept)
        self.buttonBox.rejected.connect(NrfaViewerDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NrfaViewerDialog)

    def retranslateUi(self, NrfaViewerDialog):
        _translate = QtCore.QCoreApplication.translate
        NrfaViewerDialog.setWindowTitle(_translate("NrfaViewerDialog", "NRFA Station Viewer"))
        self.workingDirGroupbox.setTitle(_translate("NrfaViewerDialog", "Set working directory"))
        self.fetchStationsGroupbox.setTitle(_translate("NrfaViewerDialog", "Fetch Stations"))
        self.label_2.setText(_translate("NrfaViewerDialog", "Max distance from map centre"))
        self.maxDistanceSpinbox.setSuffix(_translate("NrfaViewerDialog", " km"))
        self.fetchStationsBtn.setText(_translate("NrfaViewerDialog", "Fetch Stations"))
        self.stationInfoGroupbox.setTitle(_translate("NrfaViewerDialog", "Station Info"))
        self.stationTabWidget.setTabText(self.stationTabWidget.indexOf(self.overviewTab), _translate("NrfaViewerDialog", "Station Info"))
        self.stationTabWidget.setTabText(self.stationTabWidget.indexOf(self.fullDetails), _translate("NrfaViewerDialog", "Full Details"))
        self.amaxResultsTable.setSortingEnabled(False)
        item = self.amaxResultsTable.horizontalHeaderItem(0)
        item.setText(_translate("NrfaViewerDialog", "Flow"))
        item = self.amaxResultsTable.horizontalHeaderItem(1)
        item.setText(_translate("NrfaViewerDialog", "Date - Time"))
        self.showAmaxGraphBtn.setText(_translate("NrfaViewerDialog", "Show Graph"))
        self.exportAmaxCsvBtn.setText(_translate("NrfaViewerDialog", "Export CSV"))
        self.stationTabWidget.setTabText(self.stationTabWidget.indexOf(self.amaxTab), _translate("NrfaViewerDialog", "AMAX"))
        self.potResultsTable.setSortingEnabled(True)
        item = self.potResultsTable.horizontalHeaderItem(0)
        item.setText(_translate("NrfaViewerDialog", "Flow"))
        item = self.potResultsTable.horizontalHeaderItem(1)
        item.setText(_translate("NrfaViewerDialog", "Date - Time"))
        self.showPotGraphBtn.setText(_translate("NrfaViewerDialog", "Show Graph"))
        self.exportPotCsvBtn.setText(_translate("NrfaViewerDialog", "Export CSV"))
        self.stationTabWidget.setTabText(self.stationTabWidget.indexOf(self.potTab), _translate("NrfaViewerDialog", "POT"))
        self.label_5.setText(_translate("NrfaViewerDialog", "Select Year"))
        self.dailyFlowsTable.setSortingEnabled(True)
        item = self.dailyFlowsTable.horizontalHeaderItem(0)
        item.setText(_translate("NrfaViewerDialog", "Year"))
        item = self.dailyFlowsTable.horizontalHeaderItem(1)
        item.setText(_translate("NrfaViewerDialog", "Date"))
        item = self.dailyFlowsTable.horizontalHeaderItem(2)
        item.setText(_translate("NrfaViewerDialog", "Value"))
        item = self.dailyFlowsTable.horizontalHeaderItem(3)
        item.setText(_translate("NrfaViewerDialog", "Q Flag"))
        self.showDailyFlowsGraphBtn.setText(_translate("NrfaViewerDialog", "Show Graph"))
        self.exportDailyFlowsCsvBtn.setText(_translate("NrfaViewerDialog", "Export CSV"))
        self.dailyFlowExportTypeCbox.setItemText(0, _translate("NrfaViewerDialog", "Export only this year"))
        self.dailyFlowExportTypeCbox.setItemText(1, _translate("NrfaViewerDialog", "Export all years"))
        self.stationTabWidget.setTabText(self.stationTabWidget.indexOf(self.dailyFlowsTab), _translate("NrfaViewerDialog", "Daily Flows"))

from qgsfilewidget import QgsFileWidget
from qgsspinbox import QgsSpinBox
