# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/ui_runvariables_check_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FmpTuflowVariablesCheckDialog(object):
    def setupUi(self, FmpTuflowVariablesCheckDialog):
        FmpTuflowVariablesCheckDialog.setObjectName("FmpTuflowVariablesCheckDialog")
        FmpTuflowVariablesCheckDialog.resize(783, 584)
        FmpTuflowVariablesCheckDialog.setSizeGripEnabled(False)
        FmpTuflowVariablesCheckDialog.setModal(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FmpTuflowVariablesCheckDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainTabWidget = QtWidgets.QTabWidget(FmpTuflowVariablesCheckDialog)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.fmpTab = QtWidgets.QWidget()
        self.fmpTab.setObjectName("fmpTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fmpTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fmpTabWidget = QtWidgets.QTabWidget(self.fmpTab)
        self.fmpTabWidget.setObjectName("fmpTabWidget")
        self.multipleCheck = QtWidgets.QWidget()
        self.multipleCheck.setObjectName("multipleCheck")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.multipleCheck)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.multipleCheck)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.fmpIefFolderFileWidget = QgsFileWidget(self.multipleCheck)
        self.fmpIefFolderFileWidget.setObjectName("fmpIefFolderFileWidget")
        self.verticalLayout_8.addWidget(self.fmpIefFolderFileWidget)
        self.fmpMultipleSummaryTable = QtWidgets.QTableWidget(self.multipleCheck)
        self.fmpMultipleSummaryTable.setObjectName("fmpMultipleSummaryTable")
        self.fmpMultipleSummaryTable.setColumnCount(18)
        self.fmpMultipleSummaryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpMultipleSummaryTable.setHorizontalHeaderItem(17, item)
        self.fmpMultipleSummaryTable.horizontalHeader().setDefaultSectionSize(150)
        self.fmpMultipleSummaryTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.fmpMultipleSummaryTable)
        self.fmpTabWidget.addTab(self.multipleCheck, "")
        self.fmpVariablesTab = QtWidgets.QWidget()
        self.fmpVariablesTab.setObjectName("fmpVariablesTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fmpVariablesTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.fmpVariablesTab)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.iefFileWidget = QgsFileWidget(self.fmpVariablesTab)
        self.iefFileWidget.setObjectName("iefFileWidget")
        self.horizontalLayout_4.addWidget(self.iefFileWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iefTableRefreshBtn = QtWidgets.QPushButton(self.fmpVariablesTab)
        self.iefTableRefreshBtn.setObjectName("iefTableRefreshBtn")
        self.horizontalLayout.addWidget(self.iefTableRefreshBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.fmpVariablesTab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.fmpVariablesTable = QtWidgets.QTableWidget(self.fmpVariablesTab)
        self.fmpVariablesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.fmpVariablesTable.setAlternatingRowColors(False)
        self.fmpVariablesTable.setObjectName("fmpVariablesTable")
        self.fmpVariablesTable.setColumnCount(5)
        self.fmpVariablesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fmpVariablesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpVariablesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpVariablesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpVariablesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpVariablesTable.setHorizontalHeaderItem(4, item)
        self.fmpVariablesTable.horizontalHeader().setDefaultSectionSize(100)
        self.fmpVariablesTable.horizontalHeader().setMinimumSectionSize(100)
        self.fmpVariablesTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.fmpVariablesTable)
        self.label_5 = QtWidgets.QLabel(self.fmpVariablesTab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.fmpFilesTable = QtWidgets.QTableWidget(self.fmpVariablesTab)
        self.fmpFilesTable.setObjectName("fmpFilesTable")
        self.fmpFilesTable.setColumnCount(2)
        self.fmpFilesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fmpFilesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpFilesTable.setHorizontalHeaderItem(1, item)
        self.fmpFilesTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.fmpFilesTable)
        self.fmpTabWidget.addTab(self.fmpVariablesTab, "")
        self.fmpDiagnosticsTab = QtWidgets.QWidget()
        self.fmpDiagnosticsTab.setObjectName("fmpDiagnosticsTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fmpDiagnosticsTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.fmpDiagnosticsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.zzdFileWidget = QgsFileWidget(self.fmpDiagnosticsTab)
        self.zzdFileWidget.setObjectName("zzdFileWidget")
        self.gridLayout.addWidget(self.zzdFileWidget, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zzdTableRefreshBtn = QtWidgets.QPushButton(self.fmpDiagnosticsTab)
        self.zzdTableRefreshBtn.setObjectName("zzdTableRefreshBtn")
        self.horizontalLayout_3.addWidget(self.zzdTableRefreshBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(self.fmpDiagnosticsTab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.fmpRunSummaryTable = QtWidgets.QTableWidget(self.fmpDiagnosticsTab)
        self.fmpRunSummaryTable.setObjectName("fmpRunSummaryTable")
        self.fmpRunSummaryTable.setColumnCount(3)
        self.fmpRunSummaryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fmpRunSummaryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpRunSummaryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpRunSummaryTable.setHorizontalHeaderItem(2, item)
        self.fmpRunSummaryTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.fmpRunSummaryTable)
        self.label_7 = QtWidgets.QLabel(self.fmpDiagnosticsTab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.fmpDiagnosticsTable = QtWidgets.QTableWidget(self.fmpDiagnosticsTab)
        self.fmpDiagnosticsTable.setObjectName("fmpDiagnosticsTable")
        self.fmpDiagnosticsTable.setColumnCount(3)
        self.fmpDiagnosticsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fmpDiagnosticsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpDiagnosticsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fmpDiagnosticsTable.setHorizontalHeaderItem(2, item)
        self.fmpDiagnosticsTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.fmpDiagnosticsTable)
        self.fmpTabWidget.addTab(self.fmpDiagnosticsTab, "")
        self.verticalLayout.addWidget(self.fmpTabWidget)
        self.mainTabWidget.addTab(self.fmpTab, "")
        self.tlfTab = QtWidgets.QWidget()
        self.tlfTab.setObjectName("tlfTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tlfTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.tlfTab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.tlfFileWidget = QgsFileWidget(self.tlfTab)
        self.tlfFileWidget.setObjectName("tlfFileWidget")
        self.verticalLayout_5.addWidget(self.tlfFileWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tlfTableRefreshBtn = QtWidgets.QPushButton(self.tlfTab)
        self.tlfTableRefreshBtn.setObjectName("tlfTableRefreshBtn")
        self.horizontalLayout_2.addWidget(self.tlfTableRefreshBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.tuflowTabWidget = QtWidgets.QTabWidget(self.tlfTab)
        self.tuflowTabWidget.setObjectName("tuflowTabWidget")
        self.tuflowVariablesTab = QtWidgets.QWidget()
        self.tuflowVariablesTab.setObjectName("tuflowVariablesTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tuflowVariablesTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tuflowVariablesTab)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.tuflowVariablesTable = QtWidgets.QTableWidget(self.tuflowVariablesTab)
        self.tuflowVariablesTable.setAlternatingRowColors(False)
        self.tuflowVariablesTable.setObjectName("tuflowVariablesTable")
        self.tuflowVariablesTable.setColumnCount(6)
        self.tuflowVariablesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowVariablesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowVariablesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowVariablesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowVariablesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowVariablesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowVariablesTable.setHorizontalHeaderItem(5, item)
        self.tuflowVariablesTable.horizontalHeader().setDefaultSectionSize(100)
        self.tuflowVariablesTable.horizontalHeader().setMinimumSectionSize(100)
        self.tuflowVariablesTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tuflowVariablesTable)
        self.label_10 = QtWidgets.QLabel(self.tuflowVariablesTab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.tuflowFilesTable = QtWidgets.QTableWidget(self.tuflowVariablesTab)
        self.tuflowFilesTable.setObjectName("tuflowFilesTable")
        self.tuflowFilesTable.setColumnCount(4)
        self.tuflowFilesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowFilesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowFilesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowFilesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowFilesTable.setHorizontalHeaderItem(3, item)
        self.tuflowFilesTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tuflowFilesTable)
        self.tuflowTabWidget.addTab(self.tuflowVariablesTab, "")
        self.tuflowDiagnosticsTab = QtWidgets.QWidget()
        self.tuflowDiagnosticsTab.setObjectName("tuflowDiagnosticsTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tuflowDiagnosticsTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tuflowDiagnosticsTab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.tuflowRunSummaryTable = QtWidgets.QTableWidget(self.tuflowDiagnosticsTab)
        self.tuflowRunSummaryTable.setObjectName("tuflowRunSummaryTable")
        self.tuflowRunSummaryTable.setColumnCount(3)
        self.tuflowRunSummaryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowRunSummaryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowRunSummaryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowRunSummaryTable.setHorizontalHeaderItem(2, item)
        self.tuflowRunSummaryTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tuflowRunSummaryTable)
        self.label_11 = QtWidgets.QLabel(self.tuflowDiagnosticsTab)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.tuflowDiagnosticsTable = QtWidgets.QTableWidget(self.tuflowDiagnosticsTab)
        self.tuflowDiagnosticsTable.setObjectName("tuflowDiagnosticsTable")
        self.tuflowDiagnosticsTable.setColumnCount(5)
        self.tuflowDiagnosticsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowDiagnosticsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowDiagnosticsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowDiagnosticsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowDiagnosticsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tuflowDiagnosticsTable.setHorizontalHeaderItem(4, item)
        self.tuflowDiagnosticsTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tuflowDiagnosticsTable)
        self.tuflowTabWidget.addTab(self.tuflowDiagnosticsTab, "")
        self.verticalLayout_5.addWidget(self.tuflowTabWidget)
        self.mainTabWidget.addTab(self.tlfTab, "")
        self.verticalLayout_3.addWidget(self.mainTabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(FmpTuflowVariablesCheckDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(FmpTuflowVariablesCheckDialog)
        self.mainTabWidget.setCurrentIndex(0)
        self.fmpTabWidget.setCurrentIndex(0)
        self.tuflowTabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(FmpTuflowVariablesCheckDialog.accept)
        self.buttonBox.rejected.connect(FmpTuflowVariablesCheckDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FmpTuflowVariablesCheckDialog)

    def retranslateUi(self, FmpTuflowVariablesCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        FmpTuflowVariablesCheckDialog.setWindowTitle(_translate("FmpTuflowVariablesCheckDialog", "Check Default FMP-TUFLOW Variables"))
        self.label_12.setText(_translate("FmpTuflowVariablesCheckDialog", "FMP IEF Folder"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "IEF"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Timestep 1D"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Timestep 2D"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(3)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Priessman Slot"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(4)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Theta"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(5)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Alpha"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(6)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Qtol"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(7)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Htol"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(8)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "DFlood"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(9)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Max Iter"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(10)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Min Iter"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(11)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Matrix Dummy"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(12)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Global Matrix Dummy"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(13)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Double Precision 1D"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(14)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "2D Scheme"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(15)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Double Precision 2D"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(16)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "2D Run Options"))
        item = self.fmpMultipleSummaryTable.horizontalHeaderItem(17)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Full Path"))
        self.fmpTabWidget.setTabText(self.fmpTabWidget.indexOf(self.multipleCheck), _translate("FmpTuflowVariablesCheckDialog", "Multiple Summary"))
        self.label.setText(_translate("FmpTuflowVariablesCheckDialog", "FMP .ief File"))
        self.iefFileWidget.setFilter(_translate("FmpTuflowVariablesCheckDialog", "*.ief"))
        self.iefTableRefreshBtn.setText(_translate("FmpTuflowVariablesCheckDialog", "Refresh"))
        self.label_3.setText(_translate("FmpTuflowVariablesCheckDialog", "Variable Settings"))
        self.fmpVariablesTable.setSortingEnabled(False)
        item = self.fmpVariablesTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Variable"))
        item = self.fmpVariablesTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Is Default?"))
        item = self.fmpVariablesTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Value"))
        item = self.fmpVariablesTable.horizontalHeaderItem(3)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Default"))
        item = self.fmpVariablesTable.horizontalHeaderItem(4)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Description"))
        self.label_5.setText(_translate("FmpTuflowVariablesCheckDialog", "Files"))
        item = self.fmpFilesTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "File Type"))
        item = self.fmpFilesTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Path"))
        self.fmpTabWidget.setTabText(self.fmpTabWidget.indexOf(self.fmpVariablesTab), _translate("FmpTuflowVariablesCheckDialog", "Variables"))
        self.label_4.setText(_translate("FmpTuflowVariablesCheckDialog", "ZZD File name"))
        self.zzdTableRefreshBtn.setText(_translate("FmpTuflowVariablesCheckDialog", "Refresh"))
        self.label_6.setText(_translate("FmpTuflowVariablesCheckDialog", "Run Summary"))
        item = self.fmpRunSummaryTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Type"))
        item = self.fmpRunSummaryTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Value"))
        item = self.fmpRunSummaryTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Description"))
        self.label_7.setText(_translate("FmpTuflowVariablesCheckDialog", "Errors and Warnings"))
        item = self.fmpDiagnosticsTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Type"))
        item = self.fmpDiagnosticsTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Count"))
        item = self.fmpDiagnosticsTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Descripton"))
        self.fmpTabWidget.setTabText(self.fmpTabWidget.indexOf(self.fmpDiagnosticsTab), _translate("FmpTuflowVariablesCheckDialog", "Diagnostics"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.fmpTab), _translate("FmpTuflowVariablesCheckDialog", "FMP"))
        self.label_2.setText(_translate("FmpTuflowVariablesCheckDialog", "TUFLOW .tlf File"))
        self.tlfFileWidget.setFilter(_translate("FmpTuflowVariablesCheckDialog", "*.tlf"))
        self.tlfTableRefreshBtn.setText(_translate("FmpTuflowVariablesCheckDialog", "Refresh"))
        self.label_9.setText(_translate("FmpTuflowVariablesCheckDialog", "Variables Settings"))
        item = self.tuflowVariablesTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Variable"))
        item = self.tuflowVariablesTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Is Default?"))
        item = self.tuflowVariablesTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Value"))
        item = self.tuflowVariablesTable.horizontalHeaderItem(3)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Default"))
        item = self.tuflowVariablesTable.horizontalHeaderItem(4)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Options"))
        item = self.tuflowVariablesTable.horizontalHeaderItem(5)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Description"))
        self.label_10.setText(_translate("FmpTuflowVariablesCheckDialog", "Files"))
        item = self.tuflowFilesTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Type"))
        item = self.tuflowFilesTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Domain"))
        item = self.tuflowFilesTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "File Name"))
        item = self.tuflowFilesTable.horizontalHeaderItem(3)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "TLF Line"))
        self.tuflowTabWidget.setTabText(self.tuflowTabWidget.indexOf(self.tuflowVariablesTab), _translate("FmpTuflowVariablesCheckDialog", "Variables"))
        self.label_8.setText(_translate("FmpTuflowVariablesCheckDialog", "Run Summary"))
        item = self.tuflowRunSummaryTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Type"))
        item = self.tuflowRunSummaryTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Value"))
        item = self.tuflowRunSummaryTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Description"))
        self.label_11.setText(_translate("FmpTuflowVariablesCheckDialog", "Checks, Warnings and Errors"))
        item = self.tuflowDiagnosticsTable.horizontalHeaderItem(0)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Type"))
        item = self.tuflowDiagnosticsTable.horizontalHeaderItem(1)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Code"))
        item = self.tuflowDiagnosticsTable.horizontalHeaderItem(2)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Count"))
        item = self.tuflowDiagnosticsTable.horizontalHeaderItem(3)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Message"))
        item = self.tuflowDiagnosticsTable.horizontalHeaderItem(4)
        item.setText(_translate("FmpTuflowVariablesCheckDialog", "Wiki Link"))
        self.tuflowTabWidget.setTabText(self.tuflowTabWidget.indexOf(self.tuflowDiagnosticsTab), _translate("FmpTuflowVariablesCheckDialog", "Diagnostics"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tlfTab), _translate("FmpTuflowVariablesCheckDialog", "TUFLOW"))

from qgsfilewidget import QgsFileWidget
